version: '3'

services:
  tras:
    build: .
    environment:
      - DB_PASSWORD=${PSQL_PASSWORD}
      - Token=${DISCORD_TOKEN}
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: any
        delay: 5s
  
  db:
    image: bitnami/postgresql:16
    environment:
      - POSTGRESQL_PASSWORD=${PSQL_PASSWORD}
      - POSTGRESQL_DATABASE=tras
    volumes:
      - ./psql_tras_db:/bitnami/postgresql
    deploy:
      restart_policy:
        condition: any
        delay: 5s
  
volumes:
  psql_tras_db: